### ISSUE TITLE
first time run on new user will fail if newly written configs are accssed

### ISSUE THREAD

**Issue by tgbugs** [tgbugs/orthauth#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/tom/git/sparc-curation/sparcur/dashboard_server.py", line 3, in <module>
    from sparcur.cli import Report, Options, __doc__ as clidoc
  File "/home/tom/git/sparc-curation/sparcur/cli.py", line 177, in <module>
    from pyontutils.core import OntResGit
  File "/home/tom/git/pyontutils/pyontutils/core.py", line 21, in <module>
    from pyontutils import combinators as cmb
  File "/home/tom/git/pyontutils/pyontutils/combinators.py", line 5, in <module>
    from pyontutils.namespaces import TEMP
  File "/home/tom/git/pyontutils/pyontutils/namespaces.py", line 7, in <module>
    from pyontutils.config import auth
  File "/home/tom/git/pyontutils/pyontutils/config.py", line 19, in <module>
    pyontutils_config_path = auth.dynamic_config._path.parent
  File "/usr/lib/python3.7/site-packages/orthauth/core.py", line 404, in dynamic_config
    ac = dc.alt_config
  File "/usr/lib/python3.7/site-packages/orthauth/core.py", line 835, in alt_config
    path = self._alt_config_path
  File "/usr/lib/python3.7/site-packages/orthauth/core.py", line 818, in _alt_config_path
    blob = self.get_blob('alt-config')
  File "/usr/lib/python3.7/site-packages/orthauth/core.py", line 223, in get_blob
    current = current[name]
TypeError: 'NoneType' object is not subscriptable


```

**Comment by tgbugs** [comment]
I think this is fixed now. If the issue crops up again reopen.
